modules:
  robot:
    PR2JointsPerception: pepper_joints
  humans:
    StampedPosePerceptionModule: human
  objects:
    ArTrackPerceptionModule: ar_track
    StaticObjectsPerceptionModule: static

pepper_joints:
  name : pepper
  right_hand : r_gripper
  left_hand : l_gripper
  head : CameraTop_optical_frame
  base : base_link

human:
  name: human_0